# Generated by Django 4.2.6 on 2023-10-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercico',
            name='ownedDevice',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
