# Generated by Django 4.2.5 on 2023-10-03 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0002_cicoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('heure', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
