# Generated by Django 4.2.5 on 2023-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0003_devicerecords_usersettings_cats_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cats/'),
        ),
    ]
