# Generated by Django 4.2.5 on 2023-10-03 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0003_tablestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablestatus',
            name='heure',
        ),
        migrations.AddField(
            model_name='tablestatus',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
