# Generated by Django 4.2.6 on 2023-10-30 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0003_devicerecords_usersettings_cats_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ownerId'),
        ),
        migrations.AlterField(
            model_name='devicerecords',
            name='deviceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='ownedDevice', verbose_name='deviceId'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='catId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CICO.cats', verbose_name='catId'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='recordId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CICO.devicerecords', verbose_name='recordId'),
        ),
    ]
