# Generated by Django 4.2.5 on 2023-11-09 09:01

import CICO.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0004_cats_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='catId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=CICO.models.cat_directory_path),
        ),
    ]
