# Generated by Django 4.2.5 on 2023-10-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0004_remove_tablestatus_heure_tablestatus_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablestatus',
            old_name='time',
            new_name='heure',
        ),
    ]
