# Generated by Django 4.2.6 on 2023-11-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0004_alter_cats_ownerid_alter_devicerecords_deviceid_and_more'),
        ('CICO', '0005_alter_cats_catid_alter_cats_image'),
    ]

    operations = [
    ]
