# Generated by Django 4.2.5 on 2023-10-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0006_alter_tablestatus_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestatus',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], default="", max_length=5),
            preserve_default=False,
        ),
    ]
