# Generated by Django 4.2.6 on 2023-11-23 12:08

import CICO.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CICO", "0006_merge_20231115_2045"),
    ]

    operations = [
        migrations.DeleteModel(name="CiCoItem",),
        migrations.DeleteModel(name="ToDoItem",),
        migrations.AddField(
            model_name="devicerecords",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=CICO.models.record_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="cats",
            name="ownerId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="devicerecords",
            name="deviceId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                to_field="ownedDevice",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="catId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CICO.cats"
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="recordId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="CICO.devicerecords",
            ),
        ),
    ]
