# Generated by Django 4.2.5 on 2023-10-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0007_tablestatus_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablestatus',
            name='genre',
        ),
    ]
