# Generated by Django 4.2.6 on 2023-11-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0007_catsadventures_delete_cicoitem_delete_todoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsadventures',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CICO.cats'),
        ),
    ]
