# Generated by Django 4.2.6 on 2023-11-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0007_delete_cicoitem_delete_todoitem_alter_cats_ownerid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
