# Generated by Django 4.2.6 on 2023-11-19 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0008_catsadventures_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catsadventures',
            name='date',
        ),
        migrations.AddField(
            model_name='catsadventures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
