# Generated by Django 4.2.6 on 2023-11-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0008_delete_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CICO.devicerecords')),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CICO.cats')),
            ],
        ),
    ]
