# Generated by Django 4.2.5 on 2023-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0008_remove_tablestatus_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
