# Generated by Django 4.2.6 on 2023-11-19 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CICO', '0009_remove_catsadventures_date_catsadventures_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsadventures',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
